# Generated by Django 3.0.5 on 2020-07-08 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impresssion', models.CharField(max_length=100, verbose_name='印象')),
                ('preset', models.BooleanField(verbose_name='系统预置')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '印象标签',
                'verbose_name_plural': '印象标签',
            },
        ),
        migrations.CreateModel(
            name='PickCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_coin_num', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='pick数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Pick币数量',
                'verbose_name_plural': 'Pick币数量',
            },
        ),
        migrations.CreateModel(
            name='KeyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=True, verbose_name='启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关键用户',
                'verbose_name_plural': '关键用户',
            },
        ),
        migrations.CreateModel(
            name='GiveImpresssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(max_length=100, verbose_name='备注')),
                ('picks', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='pick数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('impresssion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impression.Impression', verbose_name='印象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '印象',
                'verbose_name_plural': '印象',
            },
        ),
    ]
