# Generated by Django 3.0.5 on 2020-07-08 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impression', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GiveImpresssion',
            new_name='GiveImpression',
        ),
        migrations.RenameField(
            model_name='giveimpression',
            old_name='impresssion',
            new_name='impression',
        ),
        migrations.RenameField(
            model_name='impression',
            old_name='impresssion',
            new_name='impression',
        ),
        migrations.AlterField(
            model_name='pickcoin',
            name='pick_coin_num',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='pick币'),
        ),
    ]
