# Generated by Django 3.0.5 on 2020-07-08 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impression', '0002_auto_20200708_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveimpression',
            name='praise_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='praise_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户'),
            preserve_default=False,
        ),
    ]
