# Generated by Django 3.0.5 on 2020-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '圈子', 'verbose_name_plural': '圈子'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': '优先级', 'verbose_name_plural': '优先级'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': '待办任务', 'verbose_name_plural': '待办任务'},
        ),
        migrations.AddField(
            model_name='community',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-05-19 11:10:00', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
