# Generated by Django 3.0.5 on 2020-06-05 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0003_auto_20200519_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_creater', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='is_todo_pool',
            field=models.BooleanField(default=False, verbose_name='任务池任务'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='is_week_todo',
            field=models.BooleanField(default=False, verbose_name='周计划'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', related_query_name='member', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_owner', to=settings.AUTH_USER_MODEL, verbose_name='主人'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(verbose_name='已完成'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='备注'),
        ),
    ]
