# Generated by Django 3.0.5 on 2020-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200605_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingSentences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField(verbose_name='有趣的句子')),
                ('auther', models.CharField(max_length=100, verbose_name='作者')),
            ],
            options={
                'verbose_name': '有趣的句子',
                'verbose_name_plural': '有趣的句子',
            },
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_todo_pool',
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_week_todo',
            field=models.BooleanField(verbose_name='周重点'),
        ),
    ]
