# Generated by Django 3.0.5 on 2020-06-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='process_status',
            field=models.CharField(choices=[('B', '创建'), ('T', '待办'), ('F', '跟进'), ('C', '完成')], default='B', max_length=1),
        ),
    ]
