# Generated by Django 3.0.5 on 2020-06-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0008_todo_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='todo_follower', to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_owner', to=settings.AUTH_USER_MODEL, verbose_name='主人'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='process_status',
            field=models.CharField(choices=[('T', '待办'), ('F', '跟进'), ('C', '完成')], default='T', max_length=1),
        ),
    ]
