# Generated by Django 3.0.5 on 2020-06-21 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20200621_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingagenda',
            name='community',
        ),
        migrations.AddField(
            model_name='meetingagenda',
            name='community',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.Community', verbose_name='圈子'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingagenda',
            name='track_record',
            field=models.TextField(blank=True, verbose_name='跟进记录'),
        ),
    ]
