# Generated by Django 3.0.5 on 2020-05-16 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200516_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 8, 47, 10, 893387), verbose_name='创建时间'),
        ),
    ]
